/**
 * Shared documentation contract every component's stories.tsx supplies via
 * `parameters.designSystem`. This is the "reusable documentation pattern" —
 * a future generated component gets the full docs page layout automatically
 * just by exporting this shape; the layout itself lives once in DocsPage.tsx,
 * not copy-pasted per component.
 */
export interface ComponentDocMeta {
  /** One or two sentences: what this component is and when to reach for it. */
  description: string;
  /** Short imperative guidance on how/where to use the component. */
  usageGuidelines: string[];
  dos: string[];
  donts: string[];
  /** Human labels for the variant prop's values, e.g. ["primary", "secondary"]. */
  variants: string[];
  /** Human labels for the states the component supports, e.g. ["default", "hover", "focus", "disabled"]. */
  states: string[];
  accessibilityNotes: string[];
  /** A short, hand-curated "quick start" snippet — not auto-extracted, so it
   *  can stay minimal/pedagogical rather than reflecting every story's args. */
  codeExample: string;
}

/** One documentation-quality or design-quality check result. */
export interface ValidationCheck {
  label: string;
  pass: boolean;
}

export type CheckTypeKey = 'tokenCompliance' | 'accessibility' | 'storybookCoverage' | 'documentationCoverage';

/** A single open (currently failing/warning) finding from a design-sync check. */
export interface ValidationIssue {
  level: 'fail' | 'warn';
  checkType: CheckTypeKey;
  /** Repo-relative path of the file the issue was found in. */
  file: string;
  /** 1-based line number, where design-sync can determine one — some
   *  checks (missing file, missing story export) are whole-file findings
   *  with no single line, and stay null rather than guessing one. */
  line: number | null;
  /** What's wrong. */
  message: string;
  /** How to fix it — see docs/design-system-rules.md /
   *  prompts/fix-validation-errors.md for the pattern each fix follows. */
  fix: string | null;
}

/** A previously-open issue that a later design-sync run no longer finds —
 *  i.e. actually caught and fixed between two runs, not asserted. */
export interface ResolvedIssue {
  checkType: CheckTypeKey;
  file: string;
  line: number | null;
  message: string;
  fix: string | null;
  /** Date (YYYY-MM-DD) of the run that first found it gone. */
  resolvedAt: string;
}

export interface CheckResult {
  pass: boolean;
  fail: number;
  warn: number;
  open: ValidationIssue[];
}

/**
 * Generated by `npm run design-sync` per component and written to
 * `ComponentName.validation.json` next to the component (and aggregated
 * into `src/design-docs/validation-report.generated.json`). DocsPage
 * imports this (a normal static JSON import, bundled at build time) to
 * render the "Validation Status" section and the DesignOps metadata block
 * — this is the pipeline link between the Validation stage and the
 * Documentation/Storybook stages, and the single source of truth every
 * other surface (dashboard, PR comments) reads rather than recomputing.
 */
export interface ComponentValidationReport {
  component: string;
  lastValidated: string;
  checks: Record<CheckTypeKey, CheckResult>;
  /** Cumulative log of issues caught and fixed across every run so far —
   *  starts empty for a component with no prior issue-level report to diff
   *  against, not backfilled from guesswork. */
  history: ResolvedIssue[];
  overall: boolean;
  /** Token utility names found in use during the token-compliance scan —
   *  the auto-derived "Design Tokens Used" list, not hand-maintained. */
  tokensUsed: string[];
}
