/**
 * Shared documentation contract every component's stories.tsx supplies via
 * `parameters.designSystem`. This is the "reusable documentation pattern" —
 * a future generated component gets the full docs page layout automatically
 * just by exporting this shape; the layout itself lives once in DocsPage.tsx,
 * not copy-pasted per component.
 */
export interface ComponentDocMeta {
  /** One or two sentences: what this component is and when to reach for it. */
  description: string;
  /** Short imperative guidance on how/where to use the component. */
  usageGuidelines: string[];
  dos: string[];
  donts: string[];
  /** Human labels for the variant prop's values, e.g. ["primary", "secondary"]. */
  variants: string[];
  /** Human labels for the states the component supports, e.g. ["default", "hover", "focus", "disabled"]. */
  states: string[];
  accessibilityNotes: string[];
  /** A short, hand-curated "quick start" snippet — not auto-extracted, so it
   *  can stay minimal/pedagogical rather than reflecting every story's args. */
  codeExample: string;
}

/** One documentation-quality or design-quality check result. */
export interface ValidationCheck {
  label: string;
  pass: boolean;
}

/**
 * Generated by `npm run design-sync` per component and written to
 * `ComponentName.validation.json` next to the component. DocsPage imports
 * this (a normal static JSON import, bundled at build time) to render the
 * "Validation Status" section and the DesignOps metadata block — this is
 * the pipeline link between the Validation stage and the Documentation/
 * Storybook stages.
 */
export interface ComponentValidationReport {
  component: string;
  lastValidated: string;
  tokenCompliance: boolean;
  accessibility: boolean;
  storybookCoverage: boolean;
  documentationCoverage: boolean;
  overall: boolean;
  /** Token utility names found in use during the token-compliance scan —
   *  the auto-derived "Design Tokens Used" list, not hand-maintained. */
  tokensUsed: string[];
}
