import type { Preview } from '@storybook/react-vite'

import '../src/index.css'
import { DocsPage } from '../src/design-docs/DocsPage'

// Mirrors Figma's own Variables panel mode switcher (On Light/On Dark/On
// Feature) — see tokens.css's [data-mode] override blocks and
// design-system-rules.md §7. Surface tokens are mode-invariant by design
// (a surface's own color never changes), so the matching canvas background
// per mode has to be picked here explicitly rather than resolved from a
// single token the way text-*/border-*/action-*/icon-*/state-* are.
const MODE_BACKGROUNDS: Record<string, string> = {
  light: 'var(--color-surface-primary)',
  dark: 'var(--color-surface-secondary)',
  feature: 'var(--color-surface-feature)',
};

const preview: Preview = {
  globalTypes: {
    mode: {
      name: 'Mode',
      description: "Figma variable mode this story's canvas resolves tokens against",
      defaultValue: 'light',
      toolbar: {
        icon: 'mirror',
        items: [
          { value: 'light', title: 'On Light' },
          { value: 'dark', title: 'On Dark' },
          { value: 'feature', title: 'On Feature' },
        ],
        dynamicTitle: true,
      },
    },
    // Brand and mode are independent axes (see tokens.css's "BRAND
    // OVERRIDES" section, generated by scripts/generate-brand-overrides.js)
    // — brand swaps every semantic token's value, mode swaps which surface
    // it's read against, and they compose. Runabout is the default and sets
    // no attribute at all, matching "anything without data-brand behaves
    // exactly as it does now."
    brand: {
      name: 'Brand',
      description: "Figma variable brand this story's tokens resolve against",
      defaultValue: 'runabout',
      toolbar: {
        icon: 'paintbrush',
        items: [
          { value: 'runabout', title: 'Runabout' },
          { value: 'northline', title: 'Northline' },
        ],
        dynamicTitle: true,
      },
    },
  },
  // A component that sets its own data-mode (Card -> feature, Button's
  // secondary variant -> dark) always wins over this for its own subtree —
  // CSS custom property scoping means the innermost override applies,
  // exactly matching Figma: a frame with its own explicit mode override
  // stays that mode regardless of what the file/page around it is set to.
  // This decorator is for every component that doesn't self-scope and
  // instead depends on ambient context (the majority — Badge, Checkbox,
  // Input/Select/Textarea, Tab, Button's other three variants), so their
  // stories can actually be previewed under all three modes the way a
  // designer would in Figma, not just their one hardcoded demo context.
  //
  // data-brand is set on this SAME element, not a separate wrapping div —
  // tokens.css's dark/feature brand overrides are written as a compound
  // selector, [data-brand='northline'][data-mode='dark'], which only
  // matches an element carrying both attributes at once. Split across two
  // nested divs, that selector would never match anything: the inner div's
  // own [data-mode='dark'] rule would still directly override every
  // mode-variant token back to Runabout's dark values for itself and its
  // descendants, since a rule matching an element directly always beats a
  // value merely inherited from an ancestor, regardless of the ancestor
  // rule's specificity. Runabout omits the attribute entirely (undefined),
  // matching "anything without data-brand behaves exactly as it does now."
  decorators: [
    // Prototypes/* stories (src/prototypes/ — see docs/design-system-rules.md
    // §9) get a short banner making clear they're exploratory, not shipped
    // system work — applied by title match so no per-story boilerplate is
    // needed, just the 'Prototypes/Name' title convention. Listed first
    // (outermost) so it always renders on Storybook's plain canvas, not
    // nested inside the mode-colored box the next decorator adds below.
    (Story, context) => {
      const title = context.title ?? '';
      const isPrototype = title.startsWith('Prototypes/');
      const isExample = title.startsWith('Examples/');
      if (!isPrototype && !isExample) return <Story />;

      const bannerStyle = {
        background: '#fff3cd',
        color: '#664d03',
        border: '1px solid #ffe69c',
        borderRadius: 6,
        padding: '8px 12px',
        marginBottom: 16,
        fontFamily: 'system-ui, sans-serif',
        fontSize: 13,
      } as const;

      return (
        <div>
          {isPrototype && (
            <div style={bannerStyle}>
              🧪 <strong>Prototype</strong> — exploratory work, not part of the
              shipped design system. Not covered by design-sync's blocking
              checks; see <code>src/prototypes/README.md</code>. The
              toolbar's Mode control has no effect here — every section sets
              its own data-mode (see below).
            </div>
          )}
          {isExample && (
            <div style={bannerStyle}>
              The toolbar's Mode control has no effect on this page — every
              section sets its own data-mode explicitly, the same
              self-scoping pattern Card.tsx uses for data-mode="feature".
            </div>
          )}
          <Story />
        </div>
      );
    },
    (Story, context) => {
      const mode = (context.globals.mode as string) ?? 'light';
      const brand = (context.globals.brand as string) ?? 'runabout';
      const title = context.title ?? '';
      // Examples/* and Prototypes/* stories are full pages, not single
      // components — every section already sets its own data-mode (see the
      // banner above), so an outer ambient data-mode here would be inert at
      // best and misleading at worst (implying the Mode control does
      // something it doesn't). Brand still has to flow through unconditionally
      // — it's the axis these full-page stories actually exist to exercise,
      // per VinesAndVinylLanding.stories.tsx's own header comment — so this
      // still wraps with data-brand, just without the mode-driven
      // background/padding shell meant for previewing a single component
      // under different ambient modes.
      if (title.startsWith('Examples/') || title.startsWith('Prototypes/')) {
        return (
          <div data-brand={brand === 'northline' ? 'northline' : undefined}>
            <Story />
          </div>
        );
      }
      return (
        <div
          data-mode={mode}
          data-brand={brand === 'northline' ? 'northline' : undefined}
          style={{
            background: MODE_BACKGROUNDS[mode] ?? MODE_BACKGROUNDS.light,
            padding: '2rem',
            minHeight: '100%',
            boxSizing: 'border-box',
          }}
        >
          <Story />
        </div>
      );
    },
  ],
  parameters: {
    controls: {
      matchers: {
       color: /(background|color)$/i,
       date: /Date$/i,
      },
    },

    a11y: {
      // 'todo' - show a11y violations in the test UI only
      // 'error' - fail CI on a11y violations
      // 'off' - skip a11y checks entirely
      test: 'todo'
    },

    // Registering this globally is what makes the design-system docs layout
    // (Description/Usage/Do-Don't/Variants/States/Tokens/A11y/Validation
    // Status/Controls/Code Example) automatic for every autodocs-tagged
    // component — see src/design-docs/DocsPage.tsx and types.ts. This
    // doesn't affect the Foundations/*.mdx pages, which are standalone docs
    // entries (a bare <Meta title="..." /> with no attached component),
    // not synthesized autodocs pages.
    docs: {
      page: DocsPage,
    },

    options: {
      storySort: {
        // Prototypes sits after Components, kept as its own top-level
        // section rather than nested under it — see
        // docs/design-system-rules.md §9. Anything not listed here
        // (Examples/*, etc.) falls after these in Storybook's default
        // order.
        order: [
          'Foundations',
          ['Colours', 'Typography', 'Spacing', 'Radius', 'Shadows', 'Motion', 'Breakpoints'],
          'Components',
          'Prototypes',
        ],
      },
    },
  },
};

export default preview;